mambudb_streams = {
    "deposit_transactions": {
        "partition_cols": ["date"],
        "reconcile_sql_path": "mambu_deposit_transactions_reconcile.sql",
        "backfill_sql_path": "mambu_deposit_transactions_ids.sql",
        "schema": {
            "reconciliation_date": "date",
            "source_min_id_for_date": "int",
            "source_max_id_for_date": "int",
            "currency_code": "string",
            "type": "string",
            "source_currency_type_transactions_total_for_date": "int",
            "source_sum_amount_for_currency_and_date": "decimal(20,2)",
            "source_total_rowcount_for_date": "int",
            "target_min_id_for_date": "int",
            "target_max_id_for_date": "int",
            "target_total_rowcount_for_date": "int",
            "target_sum_amount_for_currency_and_date": "decimal(20,2)",
            "target_currency_type_transactions_total_for_date": "int",
            "timestamp_extracted": "timestamp",
        },
        "columns_to_check": ["total_rowcount_for_date"],
        "processing_function": "process_deposit_transactions",
    },
    "gl_journal_entries": {
        "partition_cols": ["date"],
        "reconcile_sql_path": "mambu_gl_journal_entries_reconcile.sql",
        "schema": {
            "reconciliation_date": "date",
            "source_total_rowcount_for_date": "int",
            "source_total_gl_journal_entries_for_date": "int",
            "target_total_rowcount_for_date": "int",
            "target_total_gl_journal_entries_for_date": "int",
            "timestamp_extracted": "timestamp",
        },
        "columns_to_check": ["total_rowcount_for_date"],
        "processing_function": "process_gl_journal_entries",
    },
    "clients": {
        "partition_cols": ["date"],
        "reconcile_sql_path": "mambu_clients_reconcile.sql",
        "schema": {
            "reconcile_date": "date",
            "source_total_rowcount_for_date": "int",
            "source_total_clients_for_date": "int",
            "target_total_rowcount_for_date": "int",
            "target_total_clients_for_date": "int",
            "timestamp_extracted": "timestamp",
        },
        "columns_to_check": ["total_clients_for_date"],
        "processing_function": "process_clients",
    },
    "deposit_accounts": {
        "partition_cols": ["date"],
        "reconcile_sql_path": "mambu_deposit_accounts_reconcile.sql",
        "schema": {
            "reconcile_date": "date",
            "source_total_rowcount_for_date": "int",
            "source_total_deposit_accounts_for_date": "int",
            "target_total_rowcount_for_date": "int",
            "target_total_deposit_accounts_for_date": "int",
            "timestamp_extracted": "timestamp",
        },
        "columns_to_check": ["total_deposit_accounts_for_date"],
        "processing_function": "process_deposit_accounts",
    },
    "gl_accounts": {
        "partition_cols": ["date"],
        "reconcile_sql_path": "mambu_gl_accounts_reconcile.sql",
        "schema": {
            "reconcile_date": "date",
            "source_total_rowcount_for_date": "int",
            "source_total_gl_accounts_for_date": "int",
            "target_total_rowcount_for_date": "int",
            "target_total_gl_accounts_for_date": "int",
            "timestamp_extracted": "timestamp",
        },
        "columns_to_check": ["total_gl_accounts_for_date"],
        "processing_function": "process_gl_accounts",
    },
    "users": {
        "partition_cols": ["date"],
        "reconcile_sql_path": "mambu_users_reconcile.sql",
        "schema": {
            "reconcile_date": "date",
            "source_total_rowcount_for_date": "int",
            "source_total_users_for_date": "int",
            "target_total_rowcount_for_date": "int",
            "target_total_users_for_date": "int",
            "timestamp_extracted": "timestamp",
        },
        "columns_to_check": ["total_users_for_date"],
        "processing_function": "process_users",
    },
    "loan_accounts": {
        "partition_cols": ["date"],
        "reconcile_sql_path": "mambu_loan_accounts_reconcile.sql",
        "schema": {
            "reconcile_date": "date",
            "source_total_rowcount_for_date": "int",
            "source_total_loan_accounts_for_date": "int",
            "target_total_rowcount_for_date": "int",
            "target_total_loan_accounts_for_date": "int",
            "timestamp_extracted": "timestamp",
        },
        "columns_to_check": ["total_loan_accounts_for_date"],
        "processing_function": "process_loan_accounts",
    },
    # "loan_transactions": {
    #     "partition_cols": ["date"],
    #     "reconcile_sql_path": "mambu_loan_transactions_reconcile.sql",
    #     "schema": {
    #         "reconcile_date": "date",
    #         "source_total_rowcount_for_date": "int",
    #         "source_total_loan_transactions_for_date": "int",
    #         "target_total_rowcount_for_date": "int",
    #         "target_total_loan_transactions_for_date": "int",
    #         "timestamp_extracted": "timestamp",
    #     },
    #     "columns_to_check": ["total_loan_transactions_for_date"],
    #     "processing_function": "process_loan_transactions",
    # },
}
