column_comments = {
    "custom_field_sets": {
        "created_date": "Date at which the custom field set was created	",
        "custom_fields": "This section lists all the custom fields associated with this set	",
        "date": "The date at which ETL extraction occurred from source to data lake",
        "encoded_key": "The encoded key of the entity, generated, globally unique",
        "id": "User-defined ID, gobally unique",
        "index_in_list": "Index representing the id of custom field values in a set.",
        "last_modified_date": "The last modified date for this record",
        "name": "User-provided name of the custom field set, unique for each set type",
        "notes": "Detailed notes about the this record",
        "timestamp_extracted": "The timestamp at which ETL extraction occurred from source to data lake",
        "type": "Supported input type",
        "usage": "Information on what record types the custom field is available for.",
    },
    "clients": {
        "activation_date": "The date when client was set as active for the first time",
        "addresses": "The addresses associated with this client information like street, city etc.",
        "approved_date": "The date at which the client was approved",
        "birth_date": "The birth date of the client to search for",
        "client_role_key": "A role which describes the intended use of a client in the system	",
        "closed_date": "date when client was closed	",
        "creation_date": "The date this client was created",
        "custom_fields": "The custom fields for this entry",
        "date": "The date at which ETL extraction occurred from source to data lake",
        "encoded_key": "Address encoded key, unique, generated",
        "first_name": "The first name, personal name, given name or forename of the client",
        "group_loan_cycle": "Number of paid and closed (with 'obligations met') accounts for this client's group, when the closing operation is reverted, this is reduced",
        "id": "The id number of the client's identification document",
        "id_documents": "The identification documents of this person",
        "last_modified_date": "The last modified date for this record",
        "last_name": "The last name, surname or family name of the client",
        "middle_name": "The middle name of the client if any",
        "notes": "Detailed notes about the document",
        "preferred_language": "The client's language of use in Mambu",
        "state": "The state of the client to search for",
        "timestamp_extracted": "The timestamp at which ETL extraction occurred from source to data lake",
    },
    "deposit_accounts": {
        "account_holder_key": "The encodedKey of the client or group (a.k.a account holder)",
        "account_holder_type": "The type of the account holder (i.e CLIENT or GROUP)",
        "account_state": "The state of the deposit account",
        "account_type": "Indicates the type of the deposit account and the product that it belongs to",
        "accrued_amounts_interest_accrued": "The amount of positive interest that has been accrued in the account",
        "accrued_amounts_overdraft_interest_accrued": "The amount of negative interest that has been accrued in the account",
        "accrued_amounts_technical_overdraft_interest_accrued": "The amount of overdraft interest that has been accrued in the account",
        "activation_date": "The date this deposit account was activated (as Organization Time)",
        "approved_date": "The date this deposit account was approved (as Organization Time)",
        "assigned_branch_key": "Key of the branch this deposit account is assigned to",
        "balances_available_balance": "The current available balance for deposit transactions",
        "balances_fees_due": "How much fees is due to be paid on this account",
        "balances_hold_balance": "The sum of all the authorization hold amounts that have DBIT as creditDebitIndicator from this account",
        "balances_locked_balance": "No operation can modify the balance of the account and get it lower than this locked balance",
        "balances_overdraft_amount": "How much money has been taken out in overdraft",
        "balances_overdraft_interest_due": "How much interest is due to be paid on this account as a result of the authorized overdraft",
        "balances_technical_overdraft_amount": "How much money has been taken out as unplanned overdraft",
        "balances_technical_overdraft_interest_due": "How much interest is due to be paid on this account as a result of the technical overdraft",
        "balances_total_balance": "The current balance of the account",
        "closed_date": "The date this deposit account was closed (as UTC)",
        "creation_date": "The date this deposit account was created (as UTC)",
        "currency_code": "The currency code",
        "custom_fields": "Custom fields",
        "custom_fields_0_field_set_id": "Custom fields 0 field set id",
        "custom_fields_0_id": "Custom fields 0 id",
        "custom_fields_0_value": "Custom fields 0 value",
        "custom_fields_1_field_set_id": "Custom fields 1 field set id",
        "custom_fields_1_id": "Custom fields 1 id",
        "custom_fields_1_value": "Custom fields 1 value",
        "custom_fields_2_field_set_id": "Custom fields 2 field set id",
        "custom_fields_2_id": "Custom fields 2 id",
        "custom_fields_2_value": "Custom fields 2 value",
        "encoded_key": "The encoded for this set of interest settings, auto generated, unique",
        "id": "The id of the deposit account, can be generated and customized, unique",
        "interest_settings_interest_payment_settings_interest_payment_dates": "The list of all dates on which the interest is payed into deposit account	",
        "interest_settings_interest_payment_settings_interest_payment_point": "The interest payment point, specifies when the interest should be paid to the account",
        "interest_settings_interest_rate_settings_encoded_key": "The encoded for this set of interest settings, auto generated, unique	",
        "interest_settings_interest_rate_settings_interest_charge_frequency": "The interest change frequency. Holds the possible values for how often is interest charged on loan or deposit accounts",
        "interest_settings_interest_rate_settings_interest_charge_frequency_count": "The count of units to apply over the interval (e.g. [x] weeks)",
        "interest_settings_interest_rate_settings_interest_rate": "The interest rate for the deposit account",
        "interest_settings_interest_rate_settings_interest_rate_terms": "How is the interest rate determined when being accrued for an account",
        "internal_controls": "Groups all fields related to internal controls",
        "internal_controls_max_withdrawal_amount": "The maximum amount allowed for a withdrawal",
        "last_account_appraisal_date": "When/if the account had last been evaluated for interest calculations/maturity (as Organization Time)",
        "last_interest_calculation_date": "When/if the account had the interest last calculated (as Organization Time)",
        "last_interest_stored_date": "When/if the account had last interest applied (stored to balance) (as Organization Time)",
        "last_modified_date": "The last date the deposit account was updated (as UTC)",
        "locked_date": "The date this deposit account was locked (as Organization Time)",
        "maturity_date": "For fixed or compulsory savings plans, this is when the account matures (as Organization Time)",
        "name": "The name of the deposit account",
        "notes": "Extra notes about this deposit account",
        "overdraft_interest_settings": "Groups all fields related to a deposit account's overdraft interest settings",
        "overdraft_settings_overdraft_limit": "How much may be taken out as overdraft, null means 0	",
        "product_type_key": "The key to the type of product that this account is based on",
        "timestamp_extracted": "The timestamp at which ETL extraction occurred from source to data lake",
    },
    "deposit_transactions": {
        "account_balances_total_balance": "The running balance owed by deposit(changed within a transaction)",
        "adjustment_transaction_key": "The key of the deposit transaction where the adjustment for this transaction was made (if any adjustment was involved)",
        "affected_amounts_fees_amount": "Amount of fees involved in a transaction that affects an account with positive balance(after completing the deposit transaction)",
        "affected_amounts_fraction_amount": "In the case of an LOAN_FRACTION_BOUGHT this represent the fraction amount which was bought from another investor(after completing the deposit transaction)",
        "affected_amounts_funds_amount": "Balance change amount involved in a transaction that affects an account with positive balance(after completing the deposit transaction)",
        "affected_amounts_interest_amount": "Amount of interest involved in a transaction that affects an account with positive balance(after completing the deposit transaction)",
        "affected_amounts_overdraft_amount": "The amount of money that was added/subtracted from the account by this transaction as overdraft(after completing the deposit transaction)",
        "affected_amounts_overdraft_fees_amount": "Fees amount involved in a transaction that affects an overdraft(after completing the deposit transaction)",
        "affected_amounts_overdraft_interest_amount": "Interest amount involved in a transaction that affects an overdraft(after completing the deposit transaction)",
        "affected_amounts_technical_overdraft_amount": "The amount of money that was added/subtracted from the account by this transaction as technical overdraft(after completing the deposit transaction)",
        "affected_amounts_technical_overdraft_interest_amount": "The amount of money that was added/subtracted from the account by this transaction as technical overdraft interest(after completing the deposit transaction)",
        "amount": "How much was added/removed in account",
        "booking_date": "The date when corresponding JE is booked (as Organization Time)",
        "branch_key": "The branch where the transaction was performed",
        "card_transaction_advice": "Whether the given request should be accepted without balance validations",
        "card_transaction_amount": "The amount of money to be withdrawn in the financial transaction.",
        "card_transaction_card_acceptor_city": "The city in which the card acceptor has the business.",
        "card_transaction_card_acceptor_country": "The country in which the card acceptor has the business.",
        "card_transaction_card_acceptor_mcc": "The Merchant Category Code of the card acceptor.",
        "card_transaction_card_acceptor_name": "The name of the card acceptor.",
        "card_transaction_card_acceptor_state": "The state in which the card acceptor has the business.",
        "card_transaction_card_acceptor_zip": "The ZIP code of the location in which the card acceptor has the business.",
        "card_transaction_card_token": "The reference token of the card.",
        "card_transaction_currency_code": "The ISO currency code in which the card reversal transaction is posted. The amounts are stored in the base currency, but the transaction can be created with a foreign currency.",
        "card_transaction_encoded_key": "The encoded key of the entity, generated, globally unique",
        "card_transaction_external_authorization_reference_id": "The external authorization hold reference ID, which relates this card transaction to a previous authorization hold.",
        "card_transaction_external_reference_id": "The external reference ID to be used to reference the card transaction in subsequent requests.",
        "card_transaction_user_transaction_time": "The formatted time at which the user made this card transaction.",
        "creation_date": "The date when this deposit transaction was created",
        "currency_code": "The currency in which this transaction was posted",
        "custom_fields": "Custom fields",
        "custom_fields_0_field_set_id": "Custom fields 0 field set id",
        "custom_fields_0_id": "Custom fields 0 id",
        "custom_fields_0_value": "Custom fields 0 value",
        "custom_fields_1_field_set_id": "Custom fields 1 field set id",
        "custom_fields_1_id": "Custom fields 1 id",
        "custom_fields_1_value": "Custom fields 1 value",
        "custom_fields_2_field_set_id": "Custom fields 2 field set id",
        "custom_fields_2_id": "Custom fields 2 id",
        "custom_fields_2_value": "Custom fields 2 value",
        "encoded_key": "The encoded key of the deposit transaction, auto generated, unique",
        "external_id": "The external id of the deposit transaction, customizable, unique",
        "fees": "All the amounts that have been applied or paid within this transaction and involved predefined fees",
        "id": "The id of the deposit transaction, auto generated, unique",
        "notes": "Extra notes about this deposit transaction",
        "original_transaction_key": "The encodedKey of the transaction that was adjusted as part of this one. Available only for adjustment transactions",
        "parent_account_key": "The key of the parent deposit account",
        "taxes": "The taxes applied within a transaction",
        "terms_interest_settings": "The interest settings, holds all the properties regarding interests for the deposit account",
        "terms_interest_settings_interest_rate": "The interest rate for the deposit account",
        "terms_overdraft_interest_settings": "Holds the deposit overdraft interest settings",
        "terms_overdraft_settings": "Holds the deposit overdraft settings for a transaction",
        "timestamp_extracted": "The timestamp at which ETL extraction occurred from source to data lake",
        "transaction_details": "Contains the details about transaction including fields like transaction channel key and channel id",
        "transaction_details_transaction_channel_id": "The id of the transaction channel associated with the transaction details.",
        "transaction_details_transaction_channel_key": "The encoded key of the transaction channel associated with the transaction details.",
        "transfer_details": "Represents the transfer details, such as the linked transaction key",
        "transfer_details_linked_deposit_transaction_key": "The key of the related deposit transaction",
        "type": "The type of the deposit transaction",
        "user_key": "The person that performed the transaction",
        "value_date": "Date of the entry (eg date of repayment or disbursal, etc.) (as Organization Time)",
    },
    "gl_accounts": {
        "activated": "Whether the Account is activated and may be used.",
        "allow_manual_journal_entries": "Indicates whether manual Journal Entries are allowed or not",
        "balance": "Indicates the balance of the GL Account. This field is populated only for GET /glaccounts endpoint.",
        "creation_date": "Indicates the creation date for this account. Stored as UTC.",
        "currency_code": "Represents a currency eg. USD, EUR.",
        "currency_currency_symbol_position": "Currency symbol position",
        "currency_digits_after_decimal": "Currency digits",
        "currency_is_base_currency": "If this the base currency or not",
        "currency_last_modified_date": "Currency last modified date",
        "currency_name": "Currency name",
        "currency_symbol": "Currency symbol",
        "encoded_key": "The encoded key of the entity, generated, globally unique",
        "gl_code": "General ledger code used to identify different account types. Also used for grouping and categorizing accounts. For instance an account code of '3201' is considered a subtype of account of '3200'.",
        "last_modified_date": "Indicates when the last modification occurred. Stored as UTC.",
        "name": "Name of the GL Account",
        "strip_trailing_zeros": "Indicates whether to strip trailing zeros.",
        "type": "Type of the GL Account",
        "usage": "Categorization of GL Account by their usage (detail - where transactions are logged, or headers, for reporting and organization purposes).",
    },
    "gl_journal_entries": {
        "account_key": "Account associated with this journal action. Maybe null if just a general journal entry",
        "amount": "The amount which was debited or credited in organisation currency",
        "booking_date": "Date/time stamp when the GL Journal Entry was recorded",
        "creation_date": "The date this GL Journal Entry was created",
        "encoded_key": "The encoded key of the entity, generated, globally unique",
        "entry_date": "Rate validity start date (as Organization Time)",
        "entry_id": "The ID of the GL Journal Entry",
        "gl_account_activated": "Whether the Account is activated and may be used.",
        "gl_account_allow_manual_journal_entries": "Indicates whether manual Journal Entries are allowed or not",
        "gl_account_creation_date": "Indicates the creation date for this account. Stored as UTC.",
        "gl_account_currency_code": "Represents a currency eg. USD, EUR.",
        "gl_account_currency_currency_symbol_position": "Currency symbol position",
        "gl_account_currency_digits_after_decimal": "Currency digits",
        "gl_account_currency_is_base_currency": "If this the base currency or not",
        "gl_account_currency_last_modified_date": "Currency last modified date",
        "gl_account_currency_name": "Currency name",
        "gl_account_currency_symbol": "Currency symbol",
        "gl_account_encoded_key": "The encoded key of the entity, generated, globally unique",
        "gl_account_gl_code": "General ledger code used to identify different account types. Also used for grouping and categorizing accounts. For instance an account code of '3201' is considered a subtype of account of '3200'.",
        "gl_account_last_modified_date": "Indicates when the last modification occurred. Stored as UTC.",
        "gl_account_name": "Name of the GL Account",
        "gl_account_strip_trailing_zeros": "boolean",
        "gl_account_type": "Type of the GL Account",
        "gl_account_usage": "Categorization of GL Account by their usage (detail - where transactions are logged, or headers, for reporting and organization purposes).",
        "product_key": "The Product associated with this journal action. Maybe null if just a general journal entry",
        "timestamp_extracted": "The timestamp at which ETL extraction occurred from source to data lake",
        "transaction_id": "An id for the transaction. Not unique.",
        "type": "The type of GL Journal Entry: debit or credit",
        "user_key": "The user encode key who performed the transaction",
    },
}

schemas = {
    "custom_field_sets": {
        "created_date": "timestamp",
        "custom_fields": "string",
        "date": "string",
        "encoded_key": "string",
        "id": "string",
        "index_in_list": "bigint",
        "last_modified_date": "timestamp",
        "name": "string",
        "notes": "string",
        "timestamp_extracted": "timestamp",
        "type": "string",
        "usage": "string",
    },
    "clients": {
        "activation_date": "timestamp",
        "addresses": "string",
        "approved_date": "timestamp",
        "birth_date": "date",
        "client_role_key": "string",
        "closed_date": "timestamp",
        "creation_date": "timestamp",
        "custom_fields": "string",
        "date": "date",
        "encoded_key": "string",
        "first_name": "string",
        "group_loan_cycle": "bigint",
        "id": "string",
        "id_documents": "string",
        "last_modified_date": "timestamp",
        "last_name": "string",
        "middle_name": "string",
        "notes": "string",
        "preferred_language": "string",
        "state": "string",
        "timestamp_extracted": "timestamp",
    },
    "deposit_accounts": {
        "account_holder_key": "string",
        "account_holder_type": "string",
        "account_state": "string",
        "account_type": "string",
        "accrued_amounts_interest_accrued": "string",
        "accrued_amounts_overdraft_interest_accrued": "string",
        "accrued_amounts_technical_overdraft_interest_accrued": "string",
        "activation_date": "string",
        "approved_date": "string",
        "assigned_branch_key": "string",
        "balances_available_balance": "string",
        "balances_fees_due": "string",
        "balances_hold_balance": "string",
        "balances_locked_balance": "string",
        "balances_overdraft_amount": "string",
        "balances_overdraft_interest_due": "string",
        "balances_technical_overdraft_amount": "string",
        "balances_technical_overdraft_interest_due": "string",
        "balances_total_balance": "string",
        "closed_date": "string",
        "creation_date": "string",
        "currency_code": "string",
        "custom_fields": "string",
        "custom_fields_0_field_set_id": "string",
        "custom_fields_0_id": "string",
        "custom_fields_0_value": "string",
        "custom_fields_1_field_set_id": "string",
        "custom_fields_1_id": "string",
        "custom_fields_1_value": "string",
        "custom_fields_2_field_set_id": "string",
        "custom_fields_2_id": "string",
        "custom_fields_2_value": "string",
        "encoded_key": "string",
        "id": "string",
        "interest_settings_interest_payment_settings_interest_payment_dates": "string",
        "interest_settings_interest_payment_settings_interest_payment_point": "string",
        "interest_settings_interest_rate_settings_encoded_key": "string",
        "interest_settings_interest_rate_settings_interest_charge_frequency": "string",
        "interest_settings_interest_rate_settings_interest_charge_frequency_count": "double",
        "interest_settings_interest_rate_settings_interest_rate": "string",
        "interest_settings_interest_rate_settings_interest_rate_terms": "string",
        "internal_controls": "string",
        "internal_controls_max_withdrawal_amount": "string",
        "last_account_appraisal_date": "string",
        "last_interest_calculation_date": "string",
        "last_interest_stored_date": "string",
        "last_modified_date": "string",
        "locked_date": "string",
        "maturity_date": "string",
        "name": "string",
        "notes": "string",
        "overdraft_interest_settings": "string",
        "overdraft_settings_overdraft_limit": "string",
        "product_type_key": "string",
        "timestamp_extracted": "timestamp",
    },
    "deposit_transactions": {
        "account_balances_total_balance": "string",
        "adjustment_transaction_key": "string",
        "affected_amounts_fees_amount": "string",
        "affected_amounts_fraction_amount": "string",
        "affected_amounts_funds_amount": "string",
        "affected_amounts_interest_amount": "string",
        "affected_amounts_overdraft_amount": "string",
        "affected_amounts_overdraft_fees_amount": "string",
        "affected_amounts_overdraft_interest_amount": "string",
        "affected_amounts_technical_overdraft_amount": "string",
        "affected_amounts_technical_overdraft_interest_amount": "string",
        "amount": "string",
        "booking_date": "string",
        "branch_key": "string",
        "card_transaction_advice": "boolean",
        "card_transaction_amount": "string",
        "card_transaction_card_acceptor_city": "string",
        "card_transaction_card_acceptor_country": "string",
        "card_transaction_card_acceptor_mcc": "double",
        "card_transaction_card_acceptor_name": "string",
        "card_transaction_card_acceptor_state": "string",
        "card_transaction_card_acceptor_zip": "string",
        "card_transaction_card_token": "string",
        "card_transaction_currency_code": "string",
        "card_transaction_encoded_key": "string",
        "card_transaction_external_authorization_reference_id": "string",
        "card_transaction_external_reference_id": "string",
        "card_transaction_user_transaction_time": "string",
        "creation_date": "string",
        "currency_code": "string",
        "custom_fields": "string",
        "custom_fields_0_field_set_id": "string",
        "custom_fields_0_id": "string",
        "custom_fields_0_value": "string",
        "custom_fields_1_field_set_id": "string",
        "custom_fields_1_id": "string",
        "custom_fields_1_value": "string",
        "custom_fields_2_field_set_id": "string",
        "custom_fields_2_id": "string",
        "custom_fields_2_value": "string",
        "encoded_key": "string",
        "external_id": "string",
        "fees": "string",
        "id": "string",
        "notes": "string",
        "original_transaction_key": "string",
        "parent_account_key": "string",
        "taxes": "string",
        "terms_interest_settings": "string",
        "terms_interest_settings_interest_rate": "string",
        "terms_overdraft_interest_settings": "string",
        "terms_overdraft_settings": "string",
        "timestamp_extracted": "timestamp",
        "transaction_details": "string",
        "transaction_details_transaction_channel_id": "string",
        "transaction_details_transaction_channel_key": "string",
        "transfer_details": "string",
        "transfer_details_linked_deposit_transaction_key": "string",
        "type": "string",
        "user_key": "string",
        "value_date": "string",
    },
    "gl_accounts": {
        "activated": "boolean",
        "allow_manual_journal_entries": "boolean",
        "balance": "string",
        "creation_date": "string",
        "currency_code": "string",
        "currency_currency_symbol_position": "string",
        "currency_digits_after_decimal": "double",
        "currency_is_base_currency": "boolean",
        "currency_last_modified_date": "string",
        "currency_name": "string",
        "currency_symbol": "string",
        "encoded_key": "string",
        "gl_code": "string",
        "last_modified_date": "string",
        "name": "string",
        "strip_trailing_zeros": "boolean",
        "type": "string",
        "usage": "string",
    },
    "gl_journal_entries": {
        "account_key": "string",
        "amount": "string",
        "booking_date": "string",
        "creation_date": "string",
        "encoded_key": "string",
        "entry_date": "string",
        "entry_id": "string",
        "gl_account_activated": "boolean",
        "gl_account_allow_manual_journal_entries": "boolean",
        "gl_account_creation_date": "string",
        "gl_account_currency_code": "string",
        "gl_account_currency_currency_symbol_position": "string",
        "gl_account_currency_digits_after_decimal": "bigint",
        "gl_account_currency_is_base_currency": "boolean",
        "gl_account_currency_last_modified_date": "string",
        "gl_account_currency_name": "string",
        "gl_account_currency_symbol": "string",
        "gl_account_encoded_key": "string",
        "gl_account_gl_code": "string",
        "gl_account_last_modified_date": "string",
        "gl_account_name": "string",
        "gl_account_strip_trailing_zeros": "boolean",
        "gl_account_type": "string",
        "gl_account_usage": "string",
        "product_key": "string",
        "timestamp_extracted": "timestamp",
        "transaction_id": "string",
        "type": "string",
        "user_key": "string",
    },
}
