column_comments = {
    "loan_accounts_installments": {
        "encoded_key": "Unique identifier for the loan installment",
        "loan_account_id": "Identifier for the associated loan account",
        "parent_account_key": "Identifier for the parent account",
        "number": "Sequential number of the installment",
        "due_date": "Date when the installment is due",
        "state": "Current state of the installment (e.g., PAID, PENDING)",
        "is_payment_holiday": "Boolean indicating if the related account has been granted a payment holiday.",
        "principal_amount_expected": "Expected principal amount for the installment",
        "principal_amount_paid": "Actual principal amount paid for the installment",
        "principal_amount_due": "Remaining principal amount due for the installment",
        "interest_amount_expected": "Expected interest amount for the installment",
        "interest_amount_paid": "Actual interest amount paid for the installment",
        "interest_amount_due": "Remaining interest amount due for the installment",
        "interest_tax_expected": "Expected interest tax for the installment",
        "interest_tax_paid": "Actual interest tax paid for the installment",
        "interest_tax_due": "Remaining interest tax due for the installment",
        "fee_amount_expected": "Expected fee amount for the installment",
        "fee_amount_paid": "Actual fee amount paid for the installment",
        "fee_amount_due": "Remaining fee amount due for the installment",
        "fee_tax_expected": "Expected fee tax for the installment",
        "fee_tax_paid": "Actual fee tax paid for the installment",
        "fee_tax_due": "Remaining fee tax due for the installment",
        "penalty_amount_expected": "Expected penalty amount for the installment",
        "penalty_amount_paid": "Actual penalty amount paid for the installment",
        "penalty_amount_due": "Remaining penalty amount due for the installment",
        "penalty_tax_expected": "Expected penalty tax for the installment",
        "penalty_tax_paid": "Actual penalty tax paid for the installment",
        "penalty_tax_due": "Remaining penalty tax due for the installment",
        "custom_fields": "Additional custom fields associated with the installment",
        "last_paid_date": "Date when the last payment was made",
        "repaid_date": "Date when the installment was fully repaid",
        "timestamp_extracted": "Timestamp at which ETL extraction occurred from mambu source to data lake",
        "fee_details": "Fee details associated with the installment",
    },
}

schemas = {
    "loan_accounts_installments": {
        "encoded_key": "string",
        "loan_account_id": "string",
        "parent_account_key": "string",
        "number": "string",
        "due_date": "timestamp",
        "state": "string",
        "is_payment_holiday": "boolean",
        "principal_amount_expected": "double",
        "principal_amount_paid": "double",
        "principal_amount_due": "double",
        "interest_amount_expected": "double",
        "interest_amount_paid": "double",
        "interest_amount_due": "double",
        "interest_tax_expected": "double",
        "interest_tax_paid": "double",
        "interest_tax_due": "double",
        "fee_amount_expected": "double",
        "fee_amount_paid": "double",
        "fee_amount_due": "double",
        "fee_tax_expected": "double",
        "fee_tax_paid": "double",
        "fee_tax_due": "double",
        "penalty_amount_expected": "double",
        "penalty_amount_paid": "double",
        "penalty_amount_due": "double",
        "penalty_tax_expected": "double",
        "penalty_tax_paid": "double",
        "penalty_tax_due": "double",
        "custom_fields": "string",
        "last_paid_date": "timestamp",
        "repaid_date": "timestamp",
        "timestamp_extracted": "timestamp",
        "fee_details": "string",
    },
}
