column_comments = {
    "users": {
        "creation_date": "",
        "last_logged_in_date": "",
        "last_modified_date": "",
        "access_administrator_access": "",
        "access_api_access": "",
        "access_can_manage_all_branches": "",
        "access_delivery_access": "",
        "access_credit_officer_access": "",
        "access_mambu_access": "",
        "access_support_access": "",
        "access_teller_access": "",
        "two_factor_authentication": "",
        "user_state": "",
        "username": "",
        "title": "",
        "email": "",
        "encoded_key": "",
        "first_name": "",
        "home_phone": "",
        "id": "",
        "language": "",
        "last_name": "",
        "mobile_phone": "",
        "notes": "",
    },
    "custom_field_sets": {
        "created_date": "Date at which the custom field set was created	",
        "custom_fields": "This section lists all the custom fields associated with this set	",
        "date": "The date at which ETL extraction occurred from source to data lake",
        "encoded_key": "The encoded key of the entity, generated, globally unique",
        "id": "User-defined ID, gobally unique",
        "index_in_list": "Index representing the id of custom field values in a set.",
        "last_modified_date": "The last modified date for this record",
        "name": "User-provided name of the custom field set, unique for each set type",
        "notes": "Detailed notes about the this record",
        "timestamp_extracted": "The timestamp at which ETL extraction occurred from source to data lake",
        "type": "Supported input type",
        "usage": "Information on what record types the custom field is available for.",
    },
    "clients": {
        "activation_date": "The date when client was set as active for the first time",
        "addresses": "The addresses associated with this client information like street, city etc.",
        "approved_date": "The date at which the client was approved",
        "birth_date": "The birth date of the client to search for",
        "client_role_key": "A role which describes the intended use of a client in the system	",
        "closed_date": "date when client was closed	",
        "creation_date": "The date this client was created",
        "custom_fields": "The custom fields for this entry",
        "date": "The date at which ETL extraction occurred from source to data lake",
        "encoded_key": "Address encoded key, unique, generated",
        "first_name": "The first name, personal name, given name or forename of the client",
        "group_loan_cycle": "Number of paid and closed (with 'obligations met') accounts for this client's group, when the closing operation is reverted, this is reduced",
        "id": "The id number of the client's identification document",
        "id_documents": "The identification documents of this person",
        "last_modified_date": "The last modified date for this record",
        "last_name": "The last name, surname or family name of the client",
        "middle_name": "The middle name of the client if any",
        "notes": "Detailed notes about the document",
        "preferred_language": "The client's language of use in Mambu",
        "state": "The state of the client to search for",
        "timestamp_extracted": "The timestamp at which ETL extraction occurred from source to data lake",
    },
    "deposit_accounts": {
        "account_holder_key": "The encodedKey of the client or group (a.k.a account holder)",
        "account_holder_type": "The type of the account holder (i.e CLIENT or GROUP)",
        "account_state": "The state of the deposit account",
        "account_type": "Indicates the type of the deposit account and the product that it belongs to",
        "accrued_amounts_interest_accrued": "The amount of positive interest that has been accrued in the account",
        "accrued_amounts_overdraft_interest_accrued": "The amount of negative interest that has been accrued in the account",
        "accrued_amounts_technical_overdraft_interest_accrued": "The amount of overdraft interest that has been accrued in the account",
        "activation_date": "The date this deposit account was activated (as Organization Time)",
        "approved_date": "The date this deposit account was approved (as Organization Time)",
        "assigned_branch_key": "Key of the branch this deposit account is assigned to",
        "balances_available_balance": "The current available balance for deposit transactions",
        "balances_fees_due": "How much fees is due to be paid on this account",
        "balances_hold_balance": "The sum of all the authorization hold amounts that have DBIT as creditDebitIndicator from this account",
        "balances_locked_balance": "No operation can modify the balance of the account and get it lower than this locked balance",
        "balances_overdraft_amount": "How much money has been taken out in overdraft",
        "balances_overdraft_interest_due": "How much interest is due to be paid on this account as a result of the authorized overdraft",
        "balances_technical_overdraft_amount": "How much money has been taken out as unplanned overdraft",
        "balances_technical_overdraft_interest_due": "How much interest is due to be paid on this account as a result of the technical overdraft",
        "balances_total_balance": "The current balance of the account",
        "closed_date": "The date this deposit account was closed (as UTC)",
        "creation_date": "The date this deposit account was created (as UTC)",
        "currency_code": "The currency code",
        "custom_fields": "Custom fields",
        "custom_fields_0_field_set_id": "Custom fields 0 field set id",
        "custom_fields_0_id": "Custom fields 0 id",
        "custom_fields_0_value": "Custom fields 0 value",
        "custom_fields_1_field_set_id": "Custom fields 1 field set id",
        "custom_fields_1_id": "Custom fields 1 id",
        "custom_fields_1_value": "Custom fields 1 value",
        "custom_fields_2_field_set_id": "Custom fields 2 field set id",
        "custom_fields_2_id": "Custom fields 2 id",
        "custom_fields_2_value": "Custom fields 2 value",
        "encoded_key": "The encoded for this set of interest settings, auto generated, unique",
        "id": "The id of the deposit account, can be generated and customized, unique",
        "interest_settings_interest_payment_settings_interest_payment_dates": "The list of all dates on which the interest is payed into deposit account	",
        "interest_settings_interest_payment_settings_interest_payment_point": "The interest payment point, specifies when the interest should be paid to the account",
        "interest_settings_interest_rate_settings_encoded_key": "The encoded for this set of interest settings, auto generated, unique	",
        "interest_settings_interest_rate_settings_interest_charge_frequency": "The interest change frequency. Holds the possible values for how often is interest charged on loan or deposit accounts",
        "interest_settings_interest_rate_settings_interest_charge_frequency_count": "The count of units to apply over the interval (e.g. [x] weeks)",
        "interest_settings_interest_rate_settings_interest_rate": "The interest rate for the deposit account",
        "interest_settings_interest_rate_settings_interest_rate_terms": "How is the interest rate determined when being accrued for an account",
        "internal_controls": "Groups all fields related to internal controls",
        "internal_controls_max_withdrawal_amount": "The maximum amount allowed for a withdrawal",
        "last_account_appraisal_date": "When/if the account had last been evaluated for interest calculations/maturity (as Organization Time)",
        "last_interest_calculation_date": "When/if the account had the interest last calculated (as Organization Time)",
        "last_interest_stored_date": "When/if the account had last interest applied (stored to balance) (as Organization Time)",
        "last_modified_date": "The last date the deposit account was updated (as UTC)",
        "locked_date": "The date this deposit account was locked (as Organization Time)",
        "maturity_date": "For fixed or compulsory savings plans, this is when the account matures (as Organization Time)",
        "name": "The name of the deposit account",
        "notes": "Extra notes about this deposit account",
        "overdraft_interest_settings": "Groups all fields related to a deposit account's overdraft interest settings",
        "overdraft_settings_overdraft_limit": "How much may be taken out as overdraft, null means 0	",
        "product_type_key": "The key to the type of product that this account is based on",
        "timestamp_extracted": "The timestamp at which ETL extraction occurred from source to data lake",
    },
    "deposit_transactions": {
        "account_balances_total_balance": "The running balance owed by deposit(changed within a transaction)",
        "adjustment_transaction_key": "The key of the deposit transaction where the adjustment for this transaction was made (if any adjustment was involved)",
        "affected_amounts_fees_amount": "Amount of fees involved in a transaction that affects an account with positive balance(after completing the deposit transaction)",
        "affected_amounts_fraction_amount": "In the case of an LOAN_FRACTION_BOUGHT this represent the fraction amount which was bought from another investor(after completing the deposit transaction)",
        "affected_amounts_funds_amount": "Balance change amount involved in a transaction that affects an account with positive balance(after completing the deposit transaction)",
        "affected_amounts_interest_amount": "Amount of interest involved in a transaction that affects an account with positive balance(after completing the deposit transaction)",
        "affected_amounts_overdraft_amount": "The amount of money that was added/subtracted from the account by this transaction as overdraft(after completing the deposit transaction)",
        "affected_amounts_overdraft_fees_amount": "Fees amount involved in a transaction that affects an overdraft(after completing the deposit transaction)",
        "affected_amounts_overdraft_interest_amount": "Interest amount involved in a transaction that affects an overdraft(after completing the deposit transaction)",
        "affected_amounts_technical_overdraft_amount": "The amount of money that was added/subtracted from the account by this transaction as technical overdraft(after completing the deposit transaction)",
        "affected_amounts_technical_overdraft_interest_amount": "The amount of money that was added/subtracted from the account by this transaction as technical overdraft interest(after completing the deposit transaction)",
        "amount": "How much was added/removed in account",
        "booking_date": "The date when corresponding JE is booked (as Organization Time)",
        "branch_key": "The branch where the transaction was performed",
        "card_transaction_advice": "Whether the given request should be accepted without balance validations",
        "card_transaction_amount": "The amount of money to be withdrawn in the financial transaction.",
        "card_transaction_card_acceptor_city": "The city in which the card acceptor has the business.",
        "card_transaction_card_acceptor_country": "The country in which the card acceptor has the business.",
        "card_transaction_card_acceptor_mcc": "The Merchant Category Code of the card acceptor.",
        "card_transaction_card_acceptor_name": "The name of the card acceptor.",
        "card_transaction_card_acceptor_state": "The state in which the card acceptor has the business.",
        "card_transaction_card_acceptor_zip": "The ZIP code of the location in which the card acceptor has the business.",
        "card_transaction_card_token": "The reference token of the card.",
        "card_transaction_currency_code": "The ISO currency code in which the card reversal transaction is posted. The amounts are stored in the base currency, but the transaction can be created with a foreign currency.",
        "card_transaction_encoded_key": "The encoded key of the entity, generated, globally unique",
        "card_transaction_external_authorization_reference_id": "The external authorization hold reference ID, which relates this card transaction to a previous authorization hold.",
        "card_transaction_external_reference_id": "The external reference ID to be used to reference the card transaction in subsequent requests.",
        "card_transaction_user_transaction_time": "The formatted time at which the user made this card transaction.",
        "creation_date": "The date when this deposit transaction was created",
        "currency_code": "The currency in which this transaction was posted",
        "custom_fields": "Custom fields",
        "custom_fields_0_field_set_id": "Custom fields 0 field set id",
        "custom_fields_0_id": "Custom fields 0 id",
        "custom_fields_0_value": "Custom fields 0 value",
        "custom_fields_1_field_set_id": "Custom fields 1 field set id",
        "custom_fields_1_id": "Custom fields 1 id",
        "custom_fields_1_value": "Custom fields 1 value",
        "custom_fields_2_field_set_id": "Custom fields 2 field set id",
        "custom_fields_2_id": "Custom fields 2 id",
        "custom_fields_2_value": "Custom fields 2 value",
        "encoded_key": "The encoded key of the deposit transaction, auto generated, unique",
        "external_id": "The external id of the deposit transaction, customizable, unique",
        "fees": "All the amounts that have been applied or paid within this transaction and involved predefined fees",
        "id": "The id of the deposit transaction, auto generated, unique",
        "notes": "Extra notes about this deposit transaction",
        "original_transaction_key": "The encodedKey of the transaction that was adjusted as part of this one. Available only for adjustment transactions",
        "parent_account_key": "The key of the parent deposit account",
        "taxes": "The taxes applied within a transaction",
        "terms_interest_settings": "The interest settings, holds all the properties regarding interests for the deposit account",
        "terms_interest_settings_interest_rate": "The interest rate for the deposit account",
        "terms_overdraft_interest_settings": "Holds the deposit overdraft interest settings",
        "terms_overdraft_settings": "Holds the deposit overdraft settings for a transaction",
        "timestamp_extracted": "The timestamp at which ETL extraction occurred from source to data lake",
        "transaction_details": "Contains the details about transaction including fields like transaction channel key and channel id",
        "transaction_details_transaction_channel_id": "The id of the transaction channel associated with the transaction details.",
        "transaction_details_transaction_channel_key": "The encoded key of the transaction channel associated with the transaction details.",
        "transfer_details": "Represents the transfer details, such as the linked transaction key",
        "transfer_details_linked_deposit_transaction_key": "The key of the related deposit transaction",
        "type": "The type of the deposit transaction",
        "user_key": "The person that performed the transaction",
        "value_date": "Date of the entry (eg date of repayment or disbursal, etc.) (as Organization Time)",
    },
    "gl_accounts": {
        "activated": "Whether the Account is activated and may be used.",
        "allow_manual_journal_entries": "Indicates whether manual Journal Entries are allowed or not",
        "balance": "Indicates the balance of the GL Account. This field is populated only for GET /glaccounts endpoint.",
        "creation_date": "Indicates the creation date for this account. Stored as UTC.",
        "currency_code": "Represents a currency eg. USD, EUR.",
        "currency_currency_symbol_position": "Currency symbol position",
        "currency_digits_after_decimal": "Currency digits",
        "currency_is_base_currency": "If this the base currency or not",
        "currency_last_modified_date": "Currency last modified date",
        "currency_name": "Currency name",
        "currency_symbol": "Currency symbol",
        "encoded_key": "The encoded key of the entity, generated, globally unique",
        "gl_code": "General ledger code used to identify different account types. Also used for grouping and categorizing accounts. For instance an account code of '3201' is considered a subtype of account of '3200'.",
        "last_modified_date": "Indicates when the last modification occurred. Stored as UTC.",
        "name": "Name of the GL Account",
        "strip_trailing_zeros": "Indicates whether to strip trailing zeros.",
        "type": "Type of the GL Account",
        "usage": "Categorization of GL Account by their usage (detail - where transactions are logged, or headers, for reporting and organization purposes).",
    },
    "gl_journal_entries": {
        "account_key": "Account associated with this journal action. Maybe null if just a general journal entry",
        "amount": "The amount which was debited or credited in organisation currency",
        "booking_date": "Date/time stamp when the GL Journal Entry was recorded",
        "creation_date": "The date this GL Journal Entry was created",
        "encoded_key": "The encoded key of the entity, generated, globally unique",
        "entry_date": "Rate validity start date (as Organization Time)",
        "entry_id": "The ID of the GL Journal Entry",
        "gl_account_activated": "Whether the Account is activated and may be used.",
        "gl_account_allow_manual_journal_entries": "Indicates whether manual Journal Entries are allowed or not",
        "gl_account_creation_date": "Indicates the creation date for this account. Stored as UTC.",
        "gl_account_currency_code": "Represents a currency eg. USD, EUR.",
        "gl_account_currency_currency_symbol_position": "Currency symbol position",
        "gl_account_currency_digits_after_decimal": "Currency digits",
        "gl_account_currency_is_base_currency": "If this the base currency or not",
        "gl_account_currency_last_modified_date": "Currency last modified date",
        "gl_account_currency_name": "Currency name",
        "gl_account_currency_symbol": "Currency symbol",
        "gl_account_encoded_key": "The encoded key of the entity, generated, globally unique",
        "gl_account_gl_code": "General ledger code used to identify different account types. Also used for grouping and categorizing accounts. For instance an account code of '3201' is considered a subtype of account of '3200'.",
        "gl_account_last_modified_date": "Indicates when the last modification occurred. Stored as UTC.",
        "gl_account_name": "Name of the GL Account",
        "gl_account_strip_trailing_zeros": "boolean",
        "gl_account_type": "Type of the GL Account",
        "gl_account_usage": "Categorization of GL Account by their usage (detail - where transactions are logged, or headers, for reporting and organization purposes).",
        "product_key": "The Product associated with this journal action. Maybe null if just a general journal entry",
        "timestamp_extracted": "The timestamp at which ETL extraction occurred from source to data lake",
        "transaction_id": "An id for the transaction. Not unique.",
        "type": "The type of GL Journal Entry: debit or credit",
        "user_key": "The user encode key who performed the transaction",
    },
    "loan_accounts": {
        "account_holder_key": "The encodedKey of the client (a.k.a account holder)",
        "account_holder_type": "The type of the account holder (i.e CLIENT)",
        "account_state": "The state of the loan account",
        "account_sub_state": "This field holds a second state for the account. Relates to life-cycle of the account - refer to mambu support for more details.",
        "accrued_interest": "The accrued interest. Represents the amount of interest that has been accrued in the account.",
        "accrued_penalty": "The accrued penalty, represents the amount of penalty that has been accrued in the account.",
        "activation_transaction_key": "The encoded key of the transaction that activated this account",
        "approved_date": "The date this loan account was approved",
        "arrears_tolerance_period": "The arrears tolerance (period or day of month) depending on the product settings",
        "assets": "A list of assets associated with the current loan account",
        "assigned_branch_key": "Key of the branch this loan account is assigned to. Loan account's branch is set to unassigned if no branch field is set",
        "assigned_centre_key": "Key of the centre this account is assigned to",
        "assigned_user_key": "Key of the user this loan is assigned to",
        "balances": "The loan account balance details.",
        "closed_date": "The date this loan was closed",
        "creation_date": "The date this loan account was created",
        "credit_arrangement_key": "The key to the line of credit where this account is registered to.",
        "currency": "Represents a currency eg. USD, EUR.",
        "days_in_arrears": "The number of days in arrears",
        "days_late": "The number of days late",
        "disbursement_details": "The the disbursement details it holds the information related to the disbursement details as disbursement date, first repayment date, disbursement fees.",
        "encoded_key": "The encoded key of the loan account, auto generated, unique",
        "funding_sources": "Shows whether the future payments are allowed or not for this account (repayment transactions with entry date set in the future)",
        "guarantors": "A list of guarantees associated with the current loan account",
        "id": "The id of the loan, can be generated and customized, unique",
        "interest_accrued_billing_cycle": "The interest that is accrued in the current billing cycle.",
        "interest_commission": "The value of the interest booked by the organization from the accounts funded by investors. Null if the funds are not enable",
        "interest_from_arrears_accrued": "The interest from arrears accrued. Represents the amount of interest from arrears that has been accrued in the account.",
        "interest_settings": "The interest settings, holds all the properties regarding interests for the loan account.",
        "last_account_appraisal_date": "When/if the account had last been evaluated for interest, principal, fees and penalties calculations (as Organization Time)",
        "last_account_applied_date": "The last interest applied date. Indicates when/if the account had last interest applied (stored to interest balance) (as Organization Time)",
        "last_account_review_date": "The last interest review date. Indicates the date the interest was reviewed last time. Stored as Organization Time.",
        "last_account_locked_date": "Holds the date when the account was set for the last time in the LOCKED state. If null, the account is not locked anymore. Stored as Organization Time",
        "last_account_modified_date": "The last date the loan was updated",
        "last_account_set_to_arrears_date": "Date when the loan account was set to last standing, or null if never set (as Organization Time)",
        "last_account_tax_rate_review_date": "The last tax rate review date. Indicates When/if the account had last tax rate checked (as Organization Time).",
        "late_payments_recalculation_method": "Overdue payments recalculation method copied from the loan product on which this account is based",
        "loan_amount": "The loan amount",
        "loan_name": "The name of the loan account.",
        "migration_event_key": "The migration event encoded key associated with this loan account. If this account was imported, track which migration event they came from.",
        "modify_interest_for_first_installment": "Adjust the interest for the first repayment when the first repayment period is different than the repayment frequency",
        "notes": "Extra notes about this loan account.",
        "original_account_key": "Key of the original rescheduled/refinanced account",
        "payment_holidays_accured_interest": "The Payment Holidays interest accrued. Represents the amount of interest that has been accrued during Payment Holidays in the account.",
        "payment_method": "The payment method. Represents the interest payment method that determines whether the payments are made Horizontally (on the Repayments) or Vertically (on the Loan Account)",
        "penalty_settings": "The penalty settings, holds all the fields regarding penalties",
        "prepayment_settings": "The prepayment settings, holds all prepayment properties.",
        "product_type_key": "The key to the type of product that this account is based on.",
        "redraw_settings": "The redraw settings for a loan account.",
        "rescheduled_account_key": "Key pointing to where this account was rescheduled/refinanced to. only not null if rescheduled",
        "settlement_account_key": "The encodedKey of the settlement account",
        "tax_rate": "he tax rate.",
        "termination_date": "The date this loan account was terminated",
        "tranches": "A list of disbursement tranches available for the current loan account.",
    },
    "loan_transactions": {
        "encoded_key": "",
        "id": "",
        "creation_date": "Extra notes about this loan transaction",
        "value_date": "Date of the entry (eg date of repayment or disbursal, etc.) (as Organization Time)",
        "booking_date": "The date when corresponding JE is booked",
        "notes": "Extra notes about this loan transaction",
        "parent_account_key": "The key of the parent loan account",
        "type": "The type of the loan transaction",
        "amount": "The amount of the payment paid in the transaction for the given type.",
        "affected_amounts_interest_amount": "How much interest pre-paid was added/removed in account, within this transaction (including taxes).",
        "affected_amounts_fees_amount": "How much fees was added/removed in account, within this transaction.",
        "taxes_tax_rate": "The tax rate that was set or changed in this transaction.",
        "taxes_tax_on_interest_amount": "How much taxes on the interest that was paid in this transaction were added/removed in account, within this transaction.",
        "taxes_deferred_tax_on_interest_amount": "How much taxes on the interest that was pre-paid were added/removed in account, within this transaction. If there is any deferred tax on interest amount set in this transaction, that amount should be included in this field.",
        "taxes_tax_on_fees_amount": "How much taxes on the fees that were paid in this transaction were added/removed in account, within this transaction.",
        "taxes_tax_on_penalty_amount": "How much taxes on the penalties that were paid in this transaction were added/removed in account, within this transaction.",
        "account_balances_total_balance": "The running balance still owed for the loan.",
        "account_balances_advance_position": "Captures the advance (prepaid) amount.",
        "account_balances_arrears_position": "Captures the arrears position amount for the account in arrears.",
        "account_balances_expected_principal_redraw": "The difference between principal balance and redraw balance after each transaction performed on the loan account.",
        "account_balances_redraw_balance": "The account redraw balance captured after the transaction update.",
        "account_balances_principal_balance": "The account redraw balance captured after the transaction update.",
        "user_key": "The user that performed the transaction",
        "branch_key": "The branch where the transaction was performed",
        "terms_interest_settings_interest_rate": "The interest rate. Represents the interest rate for the loan account. The interest on loans is accrued on a daily basis, which allows charging the clients only for the days they actually used the loan amount.",
        "transaction_details_transaction_channel_key": "The encoded key of the transaction channel associated with the transaction details.",
        "transaction_details_transaction_channel_id": "The id of the transaction channel associated with the transaction details.",
        "fees_0_predefined_fee_key": "The amount of the taxes on fee that was applied/paid in the transaction.",
        "fees_0_name": "The name of the predefined fee",
        "fees_0_amount": "The amount of the fee that was applied/paid in the transaction for the given predefined fee.",
        "fees_0_tax_amount": "The amount of the taxes on fee that was applied/paid in the transaction.",
        "fees_0_trigger": "Shows the event that will trigger a fee",
    },
    "loan_products": {
        "account_link_settings_enabled": "Shows whether the loan accounts created using this product can be linked to a savings account.",
        "account_link_settings_linkable_deposit_product_key": "Loan accounts created for this product can only be linked the the savings accounts that use the savings product with this key. If null, the loan accounts for this product can be linked to any savings account.",
        "account_link_settings_linked_account_options": "A set of linked account options.",
        "account_link_settings_settlement_method": "Set the option of automated transfer that should be made from linked deposit accounts into loan accounts create from this product.",
        "accounting_settings_accounting_method": "A list of accounting rules for the product.",
        "accounting_settings_accounting_rules_encoded_key": "The encoded key of the accounting rule, auto generated, unique.",
        "accounting_settings_accounting_rules_financial_resource": "General Ledger Financial Resources used to setup the product accounting rules and determine the credit and debit accounts when logging journal entries",
        "accounting_settings_accounting_rules_gl_account_key": "The encoded key of the account that is mapped to the financialResource",
        "accounting_settings_accounting_rules_transaction_channel_key": "The key of the transaction rule that uses this rule",
        "accounting_settings_interest_accrual_calculation": "The accounting interest calculation option selected for the product.",
        "accounting_settings_interest_accrued_accounting_method": "A list of accounting rules for the product.",
        "adjust_interest_for_first_installment": "Adjust the interest for the first repayment when the first repayment period is different than the repayment frequency",
        "allow_custom_repayment_allocation": "Whether a payment could be customly allocated on the account, ignoring the default repayment allocation order",
        "arrears_settings_date_calculation_method": "The arrears date calculation method.",
        "arrears_settings_encoded_key": "The encoded key of the arrears base settings, auto generated, unique.",
        "arrears_settings_monthly_tolerance_day": "Defines the tolerance monthly date",
        "arrears_settings_non_working_days_method": "Shows whether the non working days are taken in consideration or not when applying penaltees/late fees or when setting an account into arrears",
        "arrears_settings_tolerance_calculation_method": "Defines the tolerance calculation method",
        "arrears_settings_tolerance_floor_amount": "The tolerance floor amount.",
        "arrears_settings_tolerance_percentage_of_outstanding_principal_default_value": "The default value, will be used in case no other value was filled in by the user.",
        "arrears_settings_tolerance_percentage_of_outstanding_principal_max_value": "The maximum value.",
        "arrears_settings_tolerance_percentage_of_outstanding_principal_min_value": "The minimum value.",
        "arrears_settings_tolerance_period_default_value": "The default value, will be used in case no other value was filled in by the user.",
        "arrears_settings_tolerance_period_encoded_key": "The encoded key of the integer constraint, auto generated, unique",
        "arrears_settings_tolerance_period_max_value": "The maximum value.",
        "arrears_settings_tolerance_period_min_value": "The minimum value.",
        "availability_settings_available_for": "Holds the entities this product is available for. i.e Individuals",
        "availability_settings_branch_settings_available_product_branches": "Holds the encoded keys of the branches this product should be available for.",
        "availability_settings_branch_settings_for_all_branches": "Indicates if this product should be available for all branches",
        "category": "Indicates the category the loan product belongs to.",
        "creation_date": "The date this loan product was created",
        "credit_arrangement_settings_credit_arrangement_requirement": "Shows whether accounts created after this product can/should be part of a line of credit.",
        "currency_code": "Fiat(ISO-4217) currency code or NON_FIAT for non fiat currencies.",
        "currency_currency_code": "Currency code for NON_FIAT currency.",
        "encoded_key": "The encoded key of the loan product, auto generated, unique",
        "fees_settings_allow_arbitrary_fees": "Only if true users will be able to apply fees, for current object, of type 'Other'; these fees can have any amount.",
        "fees_settings_fees_amortization_settings_amortization_profile": "Type of amortization profile used for fee",
        "fees_settings_fees_amortization_settings_encoded_key": "The encoded key of the period interval settings, auto generated, unique.",
        "fees_settings_fees_amortization_settings_fee_amortization_upon_reschedule_refinance_option": "Flag for signaling if fee amortization should be continued or finished at account reschedule/refinance",
        "fees_settings_fees_amortization_settings_frequency": "Frequency settings of the fee amortization",
        "fees_settings_fees_amortization_settings_interval_count": "Total number of intervals",
        "fees_settings_fees_amortization_settings_interval_type": "Defines the options for an interval",
        "fees_settings_fees_amortization_settings_period_count": "Period count used in conjunction with periodUnit to determine the next date of the interval",
        "fees_settings_fees_amortization_settings_period_unit": "Amortization unit to determine the interval between amortizations",
        "fees_settings_fees_amount": "The amount of the fee",
        "fees_settings_fees_amount_calculation_method": "The amount from which the fee is calculated using percentageAmount",
        "fees_settings_fees_apply_date_method": "Shows when a fee should be applied; to be used with monthly deposit fees",
        "fees_settings_fees_creation_date": "Shows the creation date of the fee",
        "fees_settings_fees_encoded_key": "The encoded key of the predefined fee, auto generated, unique",
        "fees_settings_fees_fee_application": "The type of fee application when disbursement is applied",
        "fees_settings_fees_id": "The id of the fee",
        "fees_settings_fees_last_modified_date": "Shows the last modified date of the fee",
        "fees_settings_fees_name": "The name of the fee",
        "fees_settings_fees_percentage_amount": "The amount of the fee in percents applied to percentSource",
        "fees_settings_fees_state": "Indicates the state of the fee",
        "fees_settings_fees_tax_settings_taxable_calculation_method": "Marks a specific fee as non-taxable (taxes are not calculated for it).Feature is in the Early Stage. To be enabled by request.",
        "fees_settings_fees_trigger": "Shows the event that will trigger a fee",
        "funding_settings_enabled": "Indicates whether the product has the investor funds enabled or not.",
        "funding_settings_funder_interest_commission_default_value": "The default value, will be used in case no other value was filled in by the user.",
        "funding_settings_funder_interest_commission_encoded_key": "The encoded key of the decimal constraint, auto generated, unique",
        "funding_settings_funder_interest_commission_max_value": "The maximum value.",
        "funding_settings_funder_interest_commission_min_value": "The minimum value.",
        "funding_settings_funder_interest_commission_allocation_type": "Define how the Interest is allocated to the investors(if the investors can define their own percentages for their own contribution to the loan, or if all of them are using the same percentage).",
        "funding_settings_lock_funds_at_approval": "Shows whether investor funds are locked or not at the loan account's approval.",
        "funding_settings_required_funds": "The required investor funds percentage, for opening an account with external funding. If null, the investor funds are not enabled.",
        "grace_period_settings_grace_period_type": "The grace period type. Representing the type of grace period which is possible for a loan account.",
        "id": "The id of the loan product, can be generated and customized, unique",
        "interest_settings_accrue_late_interest": "Whether late interest should be accrued, applied and paid",
        "interest_settings_compounding_frequency": "The frequency on which the accrued interest will be added to the principal for interest calculation. It is used only for InterestType.COMPOUNDING_INTEREST",
        "interest_settings_days_in_year": "The days in year that should be used for loan calculations.",
        "interest_settings_index_rate_settings_accrue_interest_after_maturity": "If the product supports this option, specify if the interest should be accrued after the account maturity date",
        "interest_settings_index_rate_settings_allow_negative_interest_rate": "Indicator whether the loan product allows negative values for interest rate or interest spread",
        "interest_settings_index_rate_settings_encoded_key": "The encoded key of the interest rate tier, auto generated, unique",
        "interest_settings_index_rate_settings_index_source_key": "Index rate source key.",
        "interest_settings_index_rate_settings_interest_charge_frequency": "The interval used for determining how often is interest charged",
        "interest_settings_index_rate_settings_interest_charge_frequency_count": "the count of units to apply over the interval",
        "interest_settings_index_rate_settings_interest_rate_ceiling_value": "Interest spread + index interest rate can't be more than this amount (valid only for index interest rate products).",
        "interest_settings_index_rate_settings_interest_rate_floor_value": "Interest spread + index interest rate can't be less than this amount (valid only for index interest rate products).",
        "interest_settings_index_rate_settings_interest_rate_review_count": "Interest rate review frequency unit count",
        "interest_settings_index_rate_settings_interest_rate_review_unit": "Interest rate review frequency measurement unit",
        "interest_settings_index_rate_settings_interest_rate_source": "Interest calculation method: fixed or (interest spread + active organization index interest rate)",
        "interest_settings_index_rate_settings_interest_rate_terms": "The option for how is the interest rate determined when being accrued for an account",
        "interest_settings_index_rate_settings_interest_rate_tiers_encoded_key": "The encoded key of the interest rate tier, auto generated, unique",
        "interest_settings_index_rate_settings_interest_rate_tiers_ending_balance": "The top-limit value for the account balance in order to determine if this tier is used or not",
        "interest_settings_index_rate_settings_interest_rate_tiers_interest_rate": "The rate used for computing the interest for an account which has the balance less than the ending balance",
        "interest_settings_interest_application_method": "The interest application method. Represents the interest application method that determines whether the interest gets applied on the account's disbursement or on each repayment.",
        "interest_settings_interest_balance_calculation_method": "The interest balance calculation method. Represents the option which determines the way the balance for the account's interest is computed.",
        "interest_settings_interest_calculation_method": "The interest calculation method. Holds the type of interest calculation method.",
        "interest_settings_interest_rate_settings_encoded_key": "The encoded key of the interest rate settings, auto generated, unique",
        "interest_settings_interest_rate_settings_index_source_key": "Index rate source key.",
        "interest_settings_interest_rate_settings_interest_rate_ceiling_value": "Maximum value allowed for index based interest rate. Valid only for index interest rate.",
        "interest_settings_interest_rate_settings_interest_rate_floor_value": "Minimum value allowed for index based interest rate. Valid only for index interest rate.",
        "interest_settings_interest_rate_settings_interest_rate_review_count": "Interest rate review frequency unit count. Valid only for index interest rate.",
        "interest_settings_interest_rate_settings_interest_rate_review_unit": "Interest rate review frequency measurement unit. Valid only for index interest rate.",
        "interest_settings_interest_rate_settings_interest_rate_source": "Interest calculation method: fixed or indexed(interest spread + active organization index interest rate)",
        "interest_settings_interest_type": "The possible values for how we compute and apply the interest",
        "interest_settings_schedule_interest_days_count_method": "Shows whether all the installments should compute the interest based on the actual number of days or based on the defined repayment periodicity.",
        "internal_controls_dormancy_period_days": "Specifies the number of days for an account to be fully paid in order to auto close it.",
        "internal_controls_four_eyes_principle_active_for_loan_approval": "Requires separate users to create and approve loan accounts",
        "internal_controls_lock_settings_capping_constraint_type": "Specifies constraint types for capping charges.",
        "internal_controls_lock_settings_capping_method": "Specifies how principal will be used when calculating capping charges.",
        "internal_controls_lock_settings_capping_percentage": "Specifies the percentage of principal that cannot be exceeded by the sum of interest, fees and penalty balances.",
        "internal_controls_lock_settings_lock_period_days": "Specifies the number of days for in which the account will be locked if it stays in arrears.",
        "last_modified_date": "The last date the loan product was updated",
        "loan_amount_settings_loan_amount_default_value": "The default value, will be used in case no other value was filled in by the user.",
        "loan_amount_settings_loan_amount_encoded_key": "The encoded key of the decimal constraint, auto generated, unique",
        "loan_amount_settings_loan_amount_max_value": "The maximum value.",
        "loan_amount_settings_loan_amount_min_value": "The minimum value.",
        "loan_amount_settings_tranche_settings_max_number_of_tranches": "The number of tranches supported by the loan product",
        "name": "The name of the loan product",
        "newaccount_settings_account_initial_state": "The initial state of the account when is created.",
        "newaccount_settings_id_generator_type": "The type of generator used for IDs creation.",
        "newaccount_settings_id_pattern": "The pattern that will be used for ID validation (as referred to as an input mask).",
        "notes": "Some notes/a description about the loan product",
        "offset_settings_allow_offset": "Indicates whether the product supports offset",
        "payment_settings_amortization_method": "Payments Method used by loan accounts for repayments schedule generation.",
        "payment_settings_late_payments_recalculation_method": "Recalculate the schedule when late payments are posted on dynamic Equal Installments loans.",
        "payment_settings_payment_method": "The payment method. Represents the interest payment method that determines whether the payments are made Horizontally (on the Repayments) or Vertically (on the Loan Account)",
        "payment_settings_prepayment_settings_apply_interest_on_prepayment_method": "Whether the interest on prepayment is applied manual or automatic.",
        "payment_settings_prepayment_settings_elements_recalculation_method": "The elements recalculation method, indicates how the declining balance with equal installments repayments are recalculated",
        "payment_settings_prepayment_settings_future_payments_acceptance": "Shows whether the future payments are allowed or not for this product (repayment transactions with entry date set in the future)",
        "payment_settings_prepayment_settings_prepayment_acceptance": "Shows whether the pre-payments are allowed or not for this product.",
        "payment_settings_prepayment_settings_prepayment_recalculation_method": "Prepayment recalculation method copied from the loan product on which this account is based",
        "payment_settings_prepayment_settings_principal_paid_installment_status": "Installment status for the case when principal is paid off (copied from loan product)",
        "payment_settings_principal_payment_settings_default_principal_repayment_interval": "How many repayments the principal has to be paid",
        "payment_settings_principal_payment_settings_encoded_key": "The encoded key of the settings, auto generated, unique",
        "payment_settings_principal_payment_settings_include_fees_in_floor_amount": "If true, the fees will be included along with the principal in the repayment floor amount, for a revolving credit account",
        "payment_settings_principal_payment_settings_include_interest_in_floor_amount": "If true, the interest will be included along with the principal in the repayment floor amount, for a revolving credit account",
        "payment_settings_principal_payment_settings_principal_ceiling_value": "The maximum principal due amount a repayment made with this settings can have",
        "payment_settings_principal_payment_settings_principal_floor_value": "The minimum principal due amount a repayment made with this settings can have",
        "payment_settings_principal_payment_settings_principal_payment_method": "The method of principal payment for revolving credit",
        "payment_settings_principal_payment_settings_total_due_amount_floor": "The minimum total due amount a repayment made with this settings can have",
        "payment_settings_principal_payment_settings_total_due_payment": "The method of total due payment for revolving credit",
        "payment_settings_repayment_allocation_order": "A list of basic repayment allocation elements such as the principal, interest & fees.",
        "penalty_settings_loan_penalty_calculation_method": "The penalty calculation method",
        "penalty_settings_loan_penalty_grace_period": "Number of days to wait before applying the loan penalty amounts",
        "redraw_settings_allow_redraw": "Indicates whether the product support redraw (prepayments which are stored at loan account level as a Redrawable balance)",
        "schedule_settings_billing_cycles_enabled": "The billing cycle status if it is enabled or disabled",
        "schedule_settings_billing_cycles_start_days": "The billing cycle start days in case it is enabled",
        "schedule_settings_default_repayment_period_count": "Interval Repayment Methodology Settings.",
        "schedule_settings_fixed_days_of_month": "Specifies the days of the month when the repayment due dates should be. Only available if the Repayment Methodology is ScheduleDueDatesMethodDTO#FIXED_DAYS_OF_MONTH.",
        "schedule_settings_interest_accrual_since": "Represents the moment the interest will start getting accrued.",
        "schedule_settings_preview_schedule_number_of_previewed_instalments": "Number of Previewed Instalments.",
        "schedule_settings_preview_schedule_preview_schedule_enabled": "Preview Schedule status.",
        "schedule_settings_repayment_method": "The repayment method value",
        "schedule_settings_repayment_period_unit": "The frequency of the loan repayment.",
        "schedule_settings_repayment_rescheduling_method": "The repayment rescheduling method used in calculations.",
        "schedule_settings_repayment_schedule_edit_options": "Shows the properties from the repayment schedule can be edited.",
        "schedule_settings_repayment_schedule_method": "The repayment schedule method. Represents the method that determines whether the schedule will be fixed all over the loan account's life cycle or will be dynamically recomputed when required.",
        "schedule_settings_rounding_settings_repayment_currency_rounding": "Specifies the repayment currency rounding method.",
        "schedule_settings_rounding_settings_repayment_elements_rounding_method": "Determines how the repayment currency rounding is handled on each element from the schedule.",
        "schedule_settings_rounding_settings_rounding_repayment_schedule_method": "Specifies the rounding repayment schedule method.",
        "schedule_settings_schedule_due_dates_method": "The methodology used by this product to compute the due dates of the repayments.",
        "schedule_settings_short_month_handling_method": "Determines how to handle the short months, if they select a fixed day of month > 28. Will be null if no such date is selected and also for the Interval methodology. Only available if the Schedule Due Dates Method is ScheduleDueDatesMethodDTO#FIXED_DAYS_OF_MONTHs.",
        "security_settings_is_collateral_enabled": "Shows whether collateral (assets or other goods) are accepted in order to reach required securities percentage from loan amount, as defined in this product.",
        "security_settings_is_guarantors_enabled": "Shows whether guarantors (other clients) are accepted in order to reach the required securities percentage from loan amount, as defined in this product.",
        "security_settings_required_guaranties": "The securities percentage from loan amount that is needed in order for this account to be approved. Null if the securities are not required.",
        "state": "Indicates the current state of the product",
        "tax_settings_tax_calculation_method": "Shows whether the tax is added on top of the target amount or not.",
        "tax_settings_tax_source_key": "The tax source from where the loan account taxes will be updated.",
        "tax_settings_taxes_on_fees_enabled": "Shows whether taxes on fees are enabled for this product or not.",
        "tax_settings_taxes_on_interest_enabled": "Shows whether taxes on interest are enabled for this product or not.",
        "tax_settings_taxes_on_penalty_enabled": "Shows whether taxes on penalties are enabled for this product or not.",
        "templates_creation_date": "The creation date of the document",
        "templates_encoded_key": "The document encodedKey",
        "templates_last_modified_date": "The last modified date of the document",
        "templates_name": "The name the document",
        "templates_type": "The type of the template",
        "type": "Indicates the type of loan product.",
    },
}

schemas = {
    "custom_field_sets": {
        "created_date": "timestamp",
        "custom_fields": "string",
        "date": "string",
        "encoded_key": "string",
        "id": "string",
        "index_in_list": "bigint",
        "last_modified_date": "timestamp",
        "name": "string",
        "notes": "string",
        "timestamp_extracted": "timestamp",
        "type": "string",
        "usage": "string",
    },
    "users": {
        "creation_date": "timestamp",
        "last_logged_in_date": "timestamp",
        "last_modified_date": "timestamp",
        "access_administrator_access": "boolean",
        "access_api_access": "boolean",
        "access_can_manage_all_branches": "boolean",
        "access_delivery_access": "boolean",
        "access_credit_officer_access": "boolean",
        "access_mambu_access": "boolean",
        "access_support_access": "boolean",
        "access_teller_access": "boolean",
        "two_factor_authentication": "boolean",
        "user_state": "string",
        "username": "string",
        "title": "string",
        "email": "string",
        "encoded_key": "string",
        "first_name": "string",
        "home_phone": "string",
        "id": "string",
        "language": "string",
        "last_name": "string",
        "mobile_phone": "string",
        "notes": "string",
    },
    "clients": {
        "activation_date": "timestamp",
        "addresses": "string",
        "approved_date": "timestamp",
        "birth_date": "date",
        "client_role_key": "string",
        "closed_date": "timestamp",
        "creation_date": "timestamp",
        "custom_fields": "string",
        "date": "date",
        "encoded_key": "string",
        "first_name": "string",
        "group_loan_cycle": "bigint",
        "id": "string",
        "id_documents": "string",
        "last_modified_date": "timestamp",
        "last_name": "string",
        "middle_name": "string",
        "notes": "string",
        "preferred_language": "string",
        "state": "string",
        "timestamp_extracted": "timestamp",
    },
    "deposit_accounts": {
        "account_holder_key": "string",
        "account_holder_type": "string",
        "account_state": "string",
        "account_type": "string",
        "accrued_amounts_interest_accrued": "string",
        "accrued_amounts_overdraft_interest_accrued": "string",
        "accrued_amounts_technical_overdraft_interest_accrued": "string",
        "activation_date": "string",
        "approved_date": "string",
        "assigned_branch_key": "string",
        "balances_available_balance": "string",
        "balances_fees_due": "string",
        "balances_hold_balance": "string",
        "balances_locked_balance": "string",
        "balances_overdraft_amount": "string",
        "balances_overdraft_interest_due": "string",
        "balances_technical_overdraft_amount": "string",
        "balances_technical_overdraft_interest_due": "string",
        "balances_total_balance": "string",
        "closed_date": "string",
        "creation_date": "string",
        "currency_code": "string",
        "custom_fields": "string",
        "custom_fields_0_field_set_id": "string",
        "custom_fields_0_id": "string",
        "custom_fields_0_value": "string",
        "custom_fields_1_field_set_id": "string",
        "custom_fields_1_id": "string",
        "custom_fields_1_value": "string",
        "custom_fields_2_field_set_id": "string",
        "custom_fields_2_id": "string",
        "custom_fields_2_value": "string",
        "encoded_key": "string",
        "id": "string",
        "interest_settings_interest_payment_settings_interest_payment_dates": "string",
        "interest_settings_interest_payment_settings_interest_payment_point": "string",
        "interest_settings_interest_rate_settings_encoded_key": "string",
        "interest_settings_interest_rate_settings_interest_charge_frequency": "string",
        "interest_settings_interest_rate_settings_interest_charge_frequency_count": "double",
        "interest_settings_interest_rate_settings_interest_rate": "string",
        "interest_settings_interest_rate_settings_interest_rate_terms": "string",
        "internal_controls": "string",
        "internal_controls_max_withdrawal_amount": "string",
        "last_account_appraisal_date": "string",
        "last_interest_calculation_date": "string",
        "last_interest_stored_date": "string",
        "last_modified_date": "string",
        "locked_date": "string",
        "maturity_date": "string",
        "name": "string",
        "notes": "string",
        "overdraft_interest_settings": "string",
        "overdraft_settings_overdraft_limit": "string",
        "product_type_key": "string",
        "timestamp_extracted": "timestamp",
    },
    "deposit_transactions": {
        "account_balances_total_balance": "string",
        "adjustment_transaction_key": "string",
        "affected_amounts_fees_amount": "string",
        "affected_amounts_fraction_amount": "string",
        "affected_amounts_funds_amount": "string",
        "affected_amounts_interest_amount": "string",
        "affected_amounts_overdraft_amount": "string",
        "affected_amounts_overdraft_fees_amount": "string",
        "affected_amounts_overdraft_interest_amount": "string",
        "affected_amounts_technical_overdraft_amount": "string",
        "affected_amounts_technical_overdraft_interest_amount": "string",
        "amount": "string",
        "booking_date": "string",
        "branch_key": "string",
        "card_transaction_advice": "boolean",
        "card_transaction_amount": "string",
        "card_transaction_card_acceptor_city": "string",
        "card_transaction_card_acceptor_country": "string",
        "card_transaction_card_acceptor_mcc": "double",
        "card_transaction_card_acceptor_name": "string",
        "card_transaction_card_acceptor_state": "string",
        "card_transaction_card_acceptor_zip": "string",
        "card_transaction_card_token": "string",
        "card_transaction_currency_code": "string",
        "card_transaction_encoded_key": "string",
        "card_transaction_external_authorization_reference_id": "string",
        "card_transaction_external_reference_id": "string",
        "card_transaction_user_transaction_time": "string",
        "creation_date": "string",
        "currency_code": "string",
        "custom_fields": "string",
        "custom_fields_0_field_set_id": "string",
        "custom_fields_0_id": "string",
        "custom_fields_0_value": "string",
        "custom_fields_1_field_set_id": "string",
        "custom_fields_1_id": "string",
        "custom_fields_1_value": "string",
        "custom_fields_2_field_set_id": "string",
        "custom_fields_2_id": "string",
        "custom_fields_2_value": "string",
        "custom_fields_3_field_set_id": "string",
        "custom_fields_3_id": "string",
        "custom_fields_3_value": "string",
        "custom_fields_4_field_set_id": "string",
        "custom_fields_4_id": "string",
        "custom_fields_4_value": "string",
        "custom_fields_5_field_set_id": "string",
        "custom_fields_5_id": "string",
        "custom_fields_5_value": "string",
        "custom_fields_6_field_set_id": "string",
        "custom_fields_6_id": "string",
        "custom_fields_6_value": "string",
        "custom_fields_7_field_set_id": "string",
        "custom_fields_7_id": "string",
        "custom_fields_7_value": "string",
        "fees_0_predefined_fee_key": "string",
        "fees_0_name": "string",
        "fees_0_amount": "string",
        "fees_0_tax_amount": "string",
        "fees_0_trigger": "string",
        "transfer_details_linked_loan_transaction_key": "string",
        "encoded_key": "string",
        "external_id": "string",
        "fees": "string",
        "id": "string",
        "notes": "string",
        "original_transaction_key": "string",
        "parent_account_key": "string",
        "taxes": "string",
        "terms_interest_settings": "string",
        "terms_interest_settings_interest_rate": "string",
        "terms_overdraft_interest_settings": "string",
        "terms_overdraft_settings": "string",
        "timestamp_extracted": "timestamp",
        "transaction_details": "string",
        "transaction_details_transaction_channel_id": "string",
        "transaction_details_transaction_channel_key": "string",
        "transfer_details": "string",
        "transfer_details_linked_deposit_transaction_key": "string",
        "type": "string",
        "user_key": "string",
        "value_date": "string",
    },
    "gl_accounts": {
        "activated": "boolean",
        "allow_manual_journal_entries": "boolean",
        "balance": "string",
        "creation_date": "string",
        "currency_code": "string",
        "currency_currency_symbol_position": "string",
        "currency_digits_after_decimal": "double",
        "currency_is_base_currency": "boolean",
        "currency_last_modified_date": "string",
        "currency_name": "string",
        "currency_symbol": "string",
        "encoded_key": "string",
        "gl_code": "string",
        "last_modified_date": "string",
        "name": "string",
        "strip_trailing_zeros": "boolean",
        "type": "string",
        "usage": "string",
    },
    "gl_journal_entries": {
        "account_key": "string",
        "amount": "string",
        "booking_date": "string",
        "creation_date": "string",
        "encoded_key": "string",
        "entry_date": "string",
        "entry_id": "string",
        "gl_account_activated": "boolean",
        "gl_account_allow_manual_journal_entries": "boolean",
        "gl_account_creation_date": "string",
        "gl_account_currency_code": "string",
        "gl_account_currency_currency_symbol_position": "string",
        "gl_account_currency_digits_after_decimal": "bigint",
        "gl_account_currency_is_base_currency": "boolean",
        "gl_account_currency_last_modified_date": "string",
        "gl_account_currency_name": "string",
        "gl_account_currency_symbol": "string",
        "gl_account_encoded_key": "string",
        "gl_account_gl_code": "string",
        "gl_account_last_modified_date": "string",
        "gl_account_name": "string",
        "gl_account_strip_trailing_zeros": "boolean",
        "gl_account_type": "string",
        "gl_account_usage": "string",
        "product_key": "string",
        "timestamp_extracted": "timestamp",
        "transaction_id": "string",
        "type": "string",
        "user_key": "string",
    },
    "loan_accounts": {
        "account_holder_key": "string",
        "account_holder_type": "string",
        "account_state": "string",
        "account_sub_state": "string",
        "accrued_interest": "double",
        "accrued_penalty": "double",
        "activation_transaction_key": "string",
        "allow_offset": "boolean",
        "approved_date": "timestamp",
        "arrears_tolerance_period": "int",
        "assets": "string",
        "assigned_branch_key": "string",
        "assigned_centre_key": "string",
        "assigned_user_key": "string",
        "closed_date": "timestamp",
        "creation_date": "timestamp",
        "credit_arrangement_key": "string",
        "currency": "string",
        "days_in_arrears": "int",
        "days_late": "int",
        "encoded_key": "string",
        "funding_sources": "string",
        "guarantors": "string",
        "id": "string",
        "interest_accrued_billing_cycle": "bigint",
        "last_account_appraisal_date": "timestamp",
        "last_account_applied_date": "timestamp",
        "last_account_review_date": "timestamp",
        "last_account_locked_date": "timestamp",
        "last_account_modified_date": "timestamp",
        "last_account_set_to_arrears_date": "timestamp",
        "last_account_tax_rate_review_date": "timestamp",
        "late_payments_recalculation_method": "string",
        "loan_amount": "double",
        "loan_name": "string",
        "migration_event_key": "string",
        "modify_interest_for_first_installment": "boolean",
        "notes": "string",
        "original_account_key": "string",
        "payment_holidays_accured_interest": "bigint",
        "payment_method": "string",
        "product_type_key": "string",
        "redraw_settings": "string",
        "rescheduled_account_key": "string",
        "settlement_account_key": "string",
        "tax_rate": "double",
        "termination_date": "timestamp",
        "last_set_to_arrears_date": "timestamp",
        "last_modified_date": "timestamp",
        "last_locked_date": "timestamp",
        "interest_from_arrears_accrued": "double",
        "last_interest_applied_date": "timestamp",
        "locked_operations": "string",
        "account_arrears_settings_encoded_key": "string",
        "account_arrears_settings_tolerance_calculation_method": "string",
        "account_arrears_settings_date_calculation_method": "string",
        "account_arrears_settings_non_working_days_method": "string",
        "account_arrears_settings_tolerance_period": "int",
        "balances_redraw_balance": "double",
        "balances_principal_due": "double",
        "balances_principal_paid": "double",
        "balances_principal_balance": "double",
        "balances_interest_due": "double",
        "balances_interest_paid": "double",
        "balances_interest_balance": "double",
        "balances_interest_from_arrears_balance": "double",
        "balances_interest_from_arrears_due": "double",
        "balances_interest_from_arrears_paid": "double",
        "balances_fees_due": "double",
        "balances_fees_paid": "double",
        "balances_fees_balance": "double",
        "balances_penalty_due": "double",
        "balances_penalty_paid": "double",
        "balances_penalty_balance": "double",
        "disbursement_details_encoded_key": "string",
        "disbursement_details_expected_disbursement_date": "timestamp",
        "disbursement_details_disbursement_date": "timestamp",
        "disbursement_details_first_repayment_date": "timestamp",
        "disbursement_details_transaction_details_encoded_key": "string",
        "disbursement_details_transaction_details_transaction_channel_key": "string",
        "disbursement_details_transaction_details_transaction_channel_id": "string",
        "disbursement_details_transaction_details_internal_transfer": "boolean",
        "disbursement_details_fees": "string",
        "prepayment_settings_prepayment_recalculation_method": "string",
        "prepayment_settings_elements_recalculation_method": "string",
        "prepayment_settings_apply_interest_on_prepayment_method": "string",
        "penalty_settings_loan_penalty_calculation_method": "string",
        "penalty_settings_penalty_rate": "double",
        "schedule_settings_has_custom_schedule": "boolean",
        "schedule_settings_default_first_repayment_due_date_offset": "int",
        "schedule_settings_principal_repayment_interval": "int",
        "schedule_settings_grace_period": "int",
        "schedule_settings_grace_period_type": "string",
        "schedule_settings_repayment_installments": "int",
        "schedule_settings_repayment_period_count": "int",
        "schedule_settings_schedule_due_dates_method": "string",
        "schedule_settings_periodic_payment": "string",
        "schedule_settings_repayment_period_unit": "string",
        "schedule_settings_repayment_schedule_method": "string",
        "schedule_settings_payment_plan": "string",
        "interest_settings_interest_rate_source": "string",
        "interest_settings_accrue_interest_after_maturity": "boolean",
        "interest_settings_interest_application_method": "string",
        "interest_settings_interest_balance_calculation_method": "string",
        "interest_settings_interest_calculation_method": "string",
        "interest_settings_interest_charge_frequency": "string",
        "interest_settings_interest_rate": "double",
        "interest_settings_interest_type": "string",
        "future_payments_acceptance": "string",
    },
    "loan_transactions": {
        "encoded_key": "string",
        "id": "string",
        "creation_date": "timestamp",
        "value_date": "timestamp",
        "booking_date": "timestamp",
        "notes": "string",
        "parent_account_key": "string",
        "type": "string",
        "amount": "double",
        "affected_amounts_interest_amount": "double",
        "affected_amounts_fees_amount": "double",
        "taxes_tax_on_interest_amount": "double",
        "taxes_deferred_tax_on_interest_amount": "double",
        "taxes_tax_on_fees_amount": "double",
        "taxes_tax_on_penalty_amount": "double",
        "taxes_tax_rate": "double",
        "account_balances_total_balance": "double",
        "account_balances_advance_position": "double",
        "account_balances_arrears_position": "double",
        "account_balances_expected_principal_redraw": "double",
        "account_balances_redraw_balance": "double",
        "account_balances_principal_balance": "double",
        "user_key": "string",
        "branch_key": "string",
        "terms_interest_settings_interest_rate": "double",
        "transaction_details_transaction_channel_key": "string",
        "transaction_details_transaction_channel_id": "string",
        "fees_0_predefined_fee_key": "string",
        "fees_0_name": "string",
        "fees_0_amount": "double",
        "fees_0_tax_amount": "double",
        "fees_0_trigger": "string",
    },
    "loan_products": {
        "account_link_settings_enabled": "boolean",
        "account_link_settings_linkable_deposit_product_key": "string",
        "account_link_settings_linked_account_options": "string",
        "account_link_settings_settlement_method": "string",
        "accounting_settings_accounting_method": "string",
        "accounting_settings_accounting_rules_encoded_key": "string",
        "accounting_settings_accounting_rules_financial_resource": "string",
        "accounting_settings_accounting_rules_gl_account_key": "string",
        "accounting_settings_accounting_rules_transaction_channel_key": "string",
        "accounting_settings_interest_accrual_calculation": "string",
        "accounting_settings_interest_accrued_accounting_method": "string",
        "adjust_interest_for_first_installment": "boolean",
        "allow_custom_repayment_allocation": "boolean",
        "arrears_settings_date_calculation_method": "string",
        "arrears_settings_encoded_key": "string",
        "arrears_settings_monthly_tolerance_day": "double",
        "arrears_settings_non_working_days_method": "string",
        "arrears_settings_tolerance_calculation_method": "string",
        "arrears_settings_tolerance_floor_amount": "double",
        "arrears_settings_tolerance_percentage_of_outstanding_principal_default_value": "double",
        "arrears_settings_tolerance_percentage_of_outstanding_principal_max_value": "double",
        "arrears_settings_tolerance_percentage_of_outstanding_principal_min_value": "double",
        "arrears_settings_tolerance_period_default_value": "double",
        "arrears_settings_tolerance_period_encoded_key": "string",
        "arrears_settings_tolerance_period_max_value": "double",
        "arrears_settings_tolerance_period_min_value": "double",
        "availability_settings_available_for": "string",
        "availability_settings_branch_settings_available_product_branches": "string",
        "availability_settings_branch_settings_for_all_branches": "boolean",
        "category": "string",
        "creation_date": "timestamp",
        "credit_arrangement_settings_credit_arrangement_requirement": "string",
        "currency_code": "string",
        "currency_currency_code": "string",
        "encoded_key": "string",
        "fees_settings_allow_arbitrary_fees": "boolean",
        "fees_settings_fees_amortization_settings_amortization_profile": "string",
        "fees_settings_fees_amortization_settings_encoded_key": "string",
        "fees_settings_fees_amortization_settings_fee_amortization_upon_reschedule_refinance_option": "string",
        "fees_settings_fees_amortization_settings_frequency": "string",
        "fees_settings_fees_amortization_settings_interval_count": "double",
        "fees_settings_fees_amortization_settings_interval_type": "string",
        "fees_settings_fees_amortization_settings_period_count": "double",
        "fees_settings_fees_amortization_settings_period_unit": "string",
        "fees_settings_fees_amount": "double",
        "fees_settings_fees_amount_calculation_method": "string",
        "fees_settings_fees_apply_date_method": "string",
        "fees_settings_fees_creation_date": "timestamp",
        "fees_settings_fees_encoded_key": "string",
        "fees_settings_fees_fee_application": "string",
        "fees_settings_fees_id": "string",
        "fees_settings_fees_last_modified_date": "timestamp",
        "fees_settings_fees_name": "string",
        "fees_settings_fees_percentage_amount": "double",
        "fees_settings_fees_state": "string",
        "fees_settings_fees_tax_settings_taxable_calculation_method": "string",
        "fees_settings_fees_trigger": "string",
        "funding_settings_enabled": "boolean",
        "funding_settings_funder_interest_commission_default_value": "double",
        "funding_settings_funder_interest_commission_encoded_key": "string",
        "funding_settings_funder_interest_commission_max_value": "double",
        "funding_settings_funder_interest_commission_min_value": "double",
        "funding_settings_funder_interest_commission_allocation_type": "string",
        "funding_settings_lock_funds_at_approval": "boolean",
        "funding_settings_required_funds": "double",
        "grace_period_settings_grace_period_type": "string",
        "id": "string",
        "interest_settings_accrue_late_interest": "boolean",
        "interest_settings_compounding_frequency": "string",
        "interest_settings_days_in_year": "string",
        "interest_settings_index_rate_settings_accrue_interest_after_maturity": "boolean",
        "interest_settings_index_rate_settings_allow_negative_interest_rate": "boolean",
        "interest_settings_index_rate_settings_encoded_key": "string",
        "interest_settings_index_rate_settings_index_source_key": "string",
        "interest_settings_index_rate_settings_interest_charge_frequency": "string",
        "interest_settings_index_rate_settings_interest_charge_frequency_count": "double",
        "interest_settings_index_rate_settings_interest_rate_ceiling_value": "double",
        "interest_settings_index_rate_settings_interest_rate_floor_value": "double",
        "interest_settings_index_rate_settings_interest_rate_review_count": "double",
        "interest_settings_index_rate_settings_interest_rate_review_unit": "string",
        "interest_settings_index_rate_settings_interest_rate_source": "string",
        "interest_settings_index_rate_settings_interest_rate_terms": "string",
        "interest_settings_index_rate_settings_interest_rate_tiers_encoded_key": "string",
        "interest_settings_index_rate_settings_interest_rate_tiers_ending_balance": "double",
        "interest_settings_index_rate_settings_interest_rate_tiers_interest_rate": "double",
        "interest_settings_interest_application_method": "string",
        "interest_settings_interest_balance_calculation_method": "string",
        "interest_settings_interest_calculation_method": "string",
        "interest_settings_interest_rate_settings_encoded_key": "string",
        "interest_settings_interest_rate_settings_index_source_key": "string",
        "interest_settings_interest_rate_settings_interest_rate_ceiling_value": "double",
        "interest_settings_interest_rate_settings_interest_rate_floor_value": "double",
        "interest_settings_interest_rate_settings_interest_rate_review_count": "double",
        "interest_settings_interest_rate_settings_interest_rate_review_unit": "string",
        "interest_settings_interest_rate_settings_interest_rate_source": "string",
        "interest_settings_interest_type": "string",
        "interest_settings_schedule_interest_days_count_method": "string",
        "internal_controls_dormancy_period_days": "double",
        "internal_controls_four_eyes_principle_active_for_loan_approval": "boolean",
        "internal_controls_lock_settings_capping_constraint_type": "string",
        "internal_controls_lock_settings_capping_method": "string",
        "internal_controls_lock_settings_capping_percentage": "double",
        "internal_controls_lock_settings_lock_period_days": "double",
        "last_modified_date": "timestamp",
        "loan_amount_settings_loan_amount_default_value": "double",
        "loan_amount_settings_loan_amount_encoded_key": "string",
        "loan_amount_settings_loan_amount_max_value": "double",
        "loan_amount_settings_loan_amount_min_value": "double",
        "loan_amount_settings_tranche_settings_max_number_of_tranches": "double",
        "name": "string",
        "newaccount_settings_account_initial_state": "string",
        "newaccount_settings_id_generator_type": "string",
        "newaccount_settings_id_pattern": "string",
        "notes": "string",
        "offset_settings_allow_offset": "boolean",
        "payment_settings_amortization_method": "string",
        "payment_settings_late_payments_recalculation_method": "string",
        "payment_settings_payment_method": "string",
        "payment_settings_prepayment_settings_apply_interest_on_prepayment_method": "string",
        "payment_settings_prepayment_settings_elements_recalculation_method": "string",
        "payment_settings_prepayment_settings_future_payments_acceptance": "string",
        "payment_settings_prepayment_settings_prepayment_acceptance": "string",
        "payment_settings_prepayment_settings_prepayment_recalculation_method": "string",
        "payment_settings_prepayment_settings_principal_paid_installment_status": "string",
        "payment_settings_principal_payment_settings_default_principal_repayment_interval": "double",
        "payment_settings_principal_payment_settings_encoded_key": "string",
        "payment_settings_principal_payment_settings_include_fees_in_floor_amount": "boolean",
        "payment_settings_principal_payment_settings_include_interest_in_floor_amount": "boolean",
        "payment_settings_principal_payment_settings_principal_ceiling_value": "double",
        "payment_settings_principal_payment_settings_principal_floor_value": "double",
        "payment_settings_principal_payment_settings_principal_payment_method": "string",
        "payment_settings_principal_payment_settings_total_due_amount_floor": "double",
        "payment_settings_principal_payment_settings_total_due_payment": "string",
        "payment_settings_repayment_allocation_order": "string",
        "penalty_settings_loan_penalty_calculation_method": "string",
        "penalty_settings_loan_penalty_grace_period": "double",
        "redraw_settings_allow_redraw": "boolean",
        "schedule_settings_billing_cycles_enabled": "boolean",
        "schedule_settings_billing_cycles_start_days": "string",
        "schedule_settings_default_repayment_period_count": "double",
        "schedule_settings_fixed_days_of_month": "string",
        "schedule_settings_interest_accrual_since": "string",
        "schedule_settings_preview_schedule_number_of_previewed_instalments": "double",
        "schedule_settings_preview_schedule_preview_schedule_enabled": "boolean",
        "schedule_settings_repayment_method": "string",
        "schedule_settings_repayment_period_unit": "string",
        "schedule_settings_repayment_rescheduling_method": "string",
        "schedule_settings_repayment_schedule_edit_options": "string",
        "schedule_settings_repayment_schedule_method": "string",
        "schedule_settings_rounding_settings_repayment_currency_rounding": "string",
        "schedule_settings_rounding_settings_repayment_elements_rounding_method": "string",
        "schedule_settings_rounding_settings_rounding_repayment_schedule_method": "string",
        "schedule_settings_schedule_due_dates_method": "string",
        "schedule_settings_short_month_handling_method": "string",
        "security_settings_is_collateral_enabled": "boolean",
        "security_settings_is_guarantors_enabled": "boolean",
        "security_settings_required_guaranties": "double",
        "state": "string",
        "tax_settings_tax_calculation_method": "string",
        "tax_settings_tax_source_key": "string",
        "tax_settings_taxes_on_fees_enabled": "boolean",
        "tax_settings_taxes_on_interest_enabled": "boolean",
        "tax_settings_taxes_on_penalty_enabled": "boolean",
        "templates_creation_date": "timestamp",
        "templates_encoded_key": "string",
        "templates_last_modified_date": "timestamp",
        "templates_name": "string",
        "templates_type": "string",
        "type": "string",
    },
}
