column_comments = {
        "gl_accounts": {
        "activated": "Whether the Account is activated and may be used.",
        "allow_manual_journal_entries": "Indicates whether manual Journal Entries are allowed or not",
        "balance": "Indicates the balance of the GL Account. This field is populated only for GET /glaccounts endpoint.",
        "creation_date": "Indicates the creation date for this account. Stored as UTC.",
        "currency_code": "Represents a currency eg. USD, EUR.",
        "currency_currency_symbol_position": "Currency symbol position",
        "currency_digits_after_decimal": "Currency digits",
        "currency_is_base_currency": "If this the base currency or not",
        "currency_last_modified_date": "Currency last modified date",
        "currency_name": "Currency name",
        "currency_symbol": "Currency symbol",
        "encoded_key": "The encoded key of the entity, generated, globally unique",
        "gl_code": "General ledger code used to identify different account types. Also used for grouping and categorizing accounts. For instance an account code of '3201' is considered a subtype of account of '3200'.",
        "last_modified_date": "Indicates when the last modification occurred. Stored as UTC.",
        "name": "Name of the GL Account",
        "strip_trailing_zeros": "Indicates whether to strip trailing zeros.",
        "type": "Type of the GL Account",
        "usage": "Categorization of GL Account by their usage (detail - where transactions are logged, or headers, for reporting and organization purposes).",
    },
}

schemas = {
    "gl_accounts": {
        "activated": "boolean",
        "allow_manual_journal_entries": "boolean",
        "balance": "string",
        "creation_date": "string",
        "currency_code": "string",
        "currency_currency_symbol_position": "string",
        "currency_digits_after_decimal": "double",
        "currency_is_base_currency": "boolean",
        "currency_last_modified_date": "string",
        "currency_name": "string",
        "currency_symbol": "string",
        "encoded_key": "string",
        "gl_code": "string",
        "last_modified_date": "string",
        "name": "string",
        "strip_trailing_zeros": "boolean",
        "type": "string",
        "usage": "string",
    },
}
